lib/lotus/routing/endpoint_resolver.rb, test/fixtures.rb, test/integration/middleware_integration_test.rb, test/routing/endpoint_resolver_test.rb
lotus/controller#72 Create a middleware endpoint for an action with one or several middlewares.
This is necessary for creating new PR in lotus/controller, fixing the rack.rb class.
Example:
```ruby
require 'lotus/router'
require 'lotus/controller'
class MyMiddleware
def initialize(app)
@app = app
end
def call(env)
code, headers, body = @app.call(env)
[code, headers.merge('X-Middleware' => 'CALLED'), body]
end
end
module Home
class Index
include Lotus::Action
use MyMiddleware
def call(params)
self.body = 'foo'
end
end
end
app = Lotus::Router.new do
get '/', to: 'home#index'
end
Rack::Server.start app: app, Port: 2300
```
I haven't added new tests, ClassEndpoint isn't tested, how is it possible to test this MiddlewareEndpoint?
=> Added middleware endpoint

Gemfile, lib/lotus/routing/nested.rb, lib/lotus/routing/resource.rb, lib/lotus/routing/resource/action.rb, lib/lotus/routing/resource/options.rb, lib/lotus/routing/resources.rb, lib/lotus/routing/resources/action.rb, test/fixtures.rb, test/integration/nested_routes_test.rb, test/namespace_test.rb, test/nested_routes_test.rb, test/resources_test.rb, test/routing/routes_inspector_test.rb
This PR adds the feature of nested routes to router:
```ruby
require 'lotus/router'
router = Lotus::Router.new do
namespace :admin do
resources :users
end
resources :users do
resources :posts
resource :avatar
end
resource :identity do
resource :api_keys
end
resource :user do
resources :comments
end
resources :users do
resources :posts do
resources :comments do
collection { get 'search' }
member     { get 'screenshot' }
end
collection { get 'search' }
member     { get 'screenshot' }
end
end
end
puts router.inspector
```
=> Nested RESTful resource(s)

lib/lotus/router.rb, lib/lotus/routing/http_router.rb, lib/lotus/routing/namespace.rb, test/prefix_test.rb
There is a problem in lotusrb gem generating correct routes when the apps are mounted inside lotus container:
```ruby
class AdminApp  < Lotus::Application
configure do
routes do
get '/home', to 'home#index', as: :home
end
end
end
Lotus::Container.configure do
mount AdminApp, at: '/admin'
mount App, at: '/'
end
AdminApp::Routes.path(:home) # => '/home' <- WRONG
AdminApp::Routes.path(:home) # => '/admin/home' <- GOOD
```
This PR add prefix option to router, later we can pass in lotusrb the `at:` option as `prefix` for the router.
```ruby
router = Lotus::Router.new(prefix: '/admin') do
get '/home', to: 'home#index', as: ':home'
end
router.path(:home) # => '/admin/home'
```
=> Added prefix option to router.

lib/lotus/routing/force_ssl.rb, lib/lotus/routing/http_router.rb, test/force_ssl_test.rb
Resolves #56 
Now you can force ssl in your router:
```ruby
@router = Lotus::Router.new(force_ssl: true) do
get '/', to: 'home#index', as: :root
end
```
if you call to your app's home then `@router` return 301 status and Location `https://localhost/`
=> Added force_ssl option

test/routing/endpoint_resolver_test.rb
Currently Rbx has problems with classes which extend `SimpleDelegator`.
See rbx issue https://github.com/rubinius/rubinius/issues/3451 for further details.
To get a better grasp what exactly was failing I added this test.
=> Add failing rbx test for EndpointResolver

lib/lotus/routing/http_router.rb, test/named_routes_test.rb, test/namespace_test.rb, test/resource_test.rb, test/resources_test.rb
Improved lotus router messages.
`No route (path) could be generated for :child - please check given arguments`
=> Added args inspect to router exception messages

lib/lotus/routing/parsing/json_parser.rb, test/routing/parsers_test.rb
The [JSON API specification](http://jsonapi.org/format/#content-negotiation) requires all requests to use the `Content-Type` `application/vnd.api+json`. Since the parameters are sent as JSON in the body, Rack ignores them. Therefore the work has to be done by Lotus, this adds the content type to the `JsonParser` so it correctly parses the requests. Otherwise the mismatch of the content types lead to missing/ignored parameters.
=> Parse JSON Body parameters for requests made with JSON API Content-Type

lib/lotus/routing/http_router.rb, lotus-router.gemspec, test/request_url_test.rb
Resolves https://github.com/lotus/lotus/issues/344
Routes from mounted apps set `SCRIPT_NAME` variable without mounted prefix.
This PR adds the prefix to this variable
=> Added prefix for mounted apps in script_name

lib/lotus/routing/force_ssl.rb, test/force_ssl_test.rb
According to Rack spec the response body must respond to #each.
Using '' as response body instead of [] causes server error
on request, when running application via ```bundle exec rackup```.
The ```bundle exec lotus server``` works normally, and correctly
forces SSL by redirecting without any error.
**To reproduce:**
```
$ lotus new force_ssl_test
```
```ruby
get '/', to: ->(env) { [200, {}, ['OK']] }
force_ssl true
```
```
$ bundle exec rackup
[2015-11-04 17:54:21] INFO  WEBrick 1.3.1
[2015-11-04 17:54:21] INFO  ruby 2.2.3 (2015-08-18) [x86_64-darwin15]
[2015-11-04 17:54:21] INFO  WEBrick::HTTPServer#start: pid=70829 port=9292
::1 - - [04/Nov/2015:17:54:31 +0300] "GET / HTTP/1.1" 301 - 0.0048
[2015-11-04 17:54:31] ERROR NoMethodError: undefined method `each' for "":String …
```
=> Make Lotus::Routing::ForceSsl respect Rack spec

lib/lotus/router.rb, test/new_test.rb, test/router_test.rb
Returns the given block as it is.
When `Lotus::Router` is used as a standalone gem and the routes are defined into a configuration file, some systems could raise an exception.
Imagine the following file into a Ruby on Rails application:
```ruby
get '/', to: 'api#index'
```
Because Ruby on Rails in production mode use to eager load code and the routes file uses top level method calls, it crashes the application.
If we wrap these routes with `Lotus::Router.define`, the block doesn't get yielded but just returned to the caller as it is.
Usually the receiver of this block is `Lotus::Router#initialize`, which finally evaluates the block.
/cc @lotus/core-team @weppos
=> Introduce Lotus::Router.define

Gemfile, README.md, lib/lotus/router.rb, lib/lotus/routing/http_router.rb, lib/lotus/routing/recognized_route.rb, test/fixtures.rb, test/recognize_test.rb
This is a proposal for better testing experience.
```ruby
require 'lotus/router'
router = Lotus::Router.new do
get '/books/:id', to: 'books#index', as: :book
end
route = router.recognize('/books/23')
route.verb   # => "GET"
route.action # => "books#index"
route.params # => {:id=>"23"}
route.routable? # => true
```
```ruby
require 'lotus/router'
router = Lotus::Router.new do
get '/books/:id', to: 'books#index', as: :book
end
env = Rack::MockRequest.env_for('/books/23')
route = router.recognize(env)
route.verb   # => "GET"
route.action # => "books#index"
route.params # => {:id=>"23"}
route.routable? # => true
```
```ruby
require 'lotus/router'
router = Lotus::Router.new do
get '/books/:id', to: 'books#index', as: :book
end
route = router.recognize(:book, id: 23)
route.verb   # => "GET" …
```
=> Introducing Lotus::Router#recognize as testing facility

README.md, lib/lotus/routing/parsing/json_parser.rb, lib/lotus/routing/parsing/parser.rb, test/routing/parsers_test.rb
Closes #46 
Raise a custom lotus exception when the json parser fails to parse a malformed json.
If you have to implement a middleware to rescue json parser errors raised from lotus json parser, you can rescue `Lotus::Routing::Parsing::JsonParsingException` exception instead `JSON::ParseError` exception.
cc @lotus/core-team
=> Custom lotus parser json exception

lib/lotus/routing/routes_inspector.rb, test/routing/routes_inspector_test.rb
This option will provide better formatting for `lotus routes` command, for example:
```
~/work/lotus_server » lotus routes
Name Method   Path                      Action
POST     /api/action               Api::Controllers::Files::Action
```
/cc @jodosha
=> Add option for display header text for routes inspector

lib/lotus/routing/routes_inspector.rb, test/routing/routes_inspector_test.rb
This PR do two things:
Firstly, it replaces conditional with polymorphism in `RoutesInspector#to_s` and it closes one TODO task.
Secondly, it fixes displaying header for `lotus routes` command(#82). Now this header shows only one time.
=> Show header for 'lotus route' command only one time

lib/hanami/routing/http_router.rb, test/request_url_test.rb, test/routing/http_router_test.rb
Why you made the change:
I made this change so that SCRIPT_NAME and PATH_INFO would be set
appropriately in the scenario where a partial match route is used.
How the change addresses the need:
There is an issue with the current version of rewrite_partial_path_info
in HttpRouter where it does not set SCRIPT_NAME appropriately. When the
request environments PATH_INFO is set, it causes the
request.rack_request.path_info helper return the updated version, not
the original. This is requst.rack_request.path_info eventually just
reads the PATH_INFO value out of the request environment. As a side
effect of this, the original code would always set the SCRIPT_NAME to ""
because it would be slicing from request.rack_request.path_info[0, 0] in
actuality.
This change resolves this issue by first …
=> Fix empty script name with partial match route bug

lib/hanami/routing/route.rb, test/routing/routes_inspector_test.rb
Why you made the change:
I did this so that non-hanami applications like Sinatra, apps, etc. when
mounted will still allow the `hanami routes` command line interface to
work.
How the change addresses the need:
As discussed in issue #92 there is an issue where when a non-hanami
application is mounted that responds to the `routes` method that doesn't
return a `Hanami::Router` it throws an exception. This change fixes that
by identifying non-hanami nested routers properly rather than just doing
it based the application responding to the `routes` method.
---
Closes #92
=> Make hanami routes work with nested non-hanami apps

lib/hanami/router.rb, test/new_test.rb, test/routing/routes_inspector_test.rb, test/routing_test.rb
Closes #97.
The guides will need to be updated, which I can do after this is merged. 
Do you think we should add support for missing the `to:`? e.g. `root "welcome#index"`
[Rails has this shortcut](http://guides.rubyonrails.org/routing.html#using-root) and it's nice.
=> Add root route

lib/hanami/routing/http_router.rb, test/integration/router_container_test.rb
This way it's possible to mount different containers on different domains. E.g.:
```
Hanami::Container.configure do
mount Admin::Application, at: '/', host: 'admin.hanami.dev'
mount Web::Application, at: '/'
end
```
=> Match against host

lib/hanami/routing/endpoint_resolver.rb
Not really sure about this PR, so I'd love to get your feedback about this small refactor.
Was thinking of moving the default response to a frozen constant, seeing that most literals in Hanami are constantized. It might save Ruby a few cycles from allocating new objects whenever the router's default endpoint needs to be called.
I also did a micro benchmark and it showed some promise:
```ruby
require 'benchmark/ips'
require 'hanami/router'
DEFAULT_RESPONSE = [404, {'X-Cascade' => 'pass'}, 'Not Found'].freeze
Benchmark.ips do |bm|
bm.report 'literal' do
Hanami::Routing::Endpoint.new(
->(env) { [404, {'X-Cascade' => 'pass'}, 'Not Found'] }
).call({})
end
bm.report 'constant' do
Hanami::Routing::Endpoint.new(
->(env) { DEFAULT_RESPONSE }
).call({})
end
bm.compare!
end
```
```
Warming up …
```
=> Move default response to a constant

lib/hanami/routing/parsers.rb, test/routing/parsers_test.rb
I did this because I want to access the body parsed with the body parsers outside of `Action#params`.  Currently the parsed body attributes are merged with route/query params as `#params`, which makes it impossible to know the source of a parameter.
=> Add parsed body to env

lib/hanami/routing/parsers.rb, test/routing/parsers_test.rb
Some middleware may need to access the pristine parsed body (via `env['router.parsed_body']`). Currently, the keys of this hash get symbolized (which is desirable for `env['router.params']` for consistency).
This PR makes it so that the keys are only symbolized in `env['router.params']`, and not in `env['router.parsed_body']`.
=> Avoid symbolizing keys of parsed body.

lib/hanami/routing/resource/action.rb, test/named_routes_test.rb, test/namespace_test.rb, test/resource_test.rb, test/resources_test.rb, test/routing/routes_inspector_test.rb
Scenario:
I am developing an application with Czech-only user interface and I want the URLs to be Czech, too. But the code is English, because it's beautiful and convenient. So I define routes like
```ruby
resources :kocky, controller: 'cats'
resources :psi, controller: 'dogs'
```
with Czech resource names mapping to English-named controllers.
The generated route names are not very satisfactory. Not only Czech and English are being mixed together, but furthermore the English pluralizer disfigures the Czech words:
```
kockies GET, HEAD  /kocky                         Web::Controllers::Cats::Index 
new_kocky GET, HEAD  /kocky/new                     Web::Controllers::Cats::New   
kockies POST       /kocky                         Web::Controllers::Cats::Create
kocky GET, HEAD  /kocky/:id …
```
=> :as option for RESTful routes

lib/hanami/routing/parsers.rb, test/routing/parsers_test.rb
Found that in hanami 1.0.0.beta1 construction like `params.get(:data, :attributes)` is not working. 
I found changes in Hanami::Utils for hash modifications. 
Now for deep symbolize need to use `#deep_symbolize!` instead of `#symbolize!`.
Also I fixed a test to check for deep params.
=> Fix issue with deep symbolize for router params

lib/hanami/routing/endpoint.rb, lib/hanami/routing/recognized_route.rb, test/recognize_test.rb
This is a fix for a problem with `Hanami::Router#recognize`. When a _lazy endpoint_ cannot be resolved, it should return a non-routeable object instead of raising `ArgumentError`.
Given the following routes:
```ruby
router = Hanami::Router.new do
get '/books', to: 'books#index'
end
```
When `"books#index"` cannot be immediately associated to an action, the router instantiate a _lazy endpoint_, which will defer the resolution on the first request.
In case the action wasn't defined at all, the router used to raise a cryptic error.
```ruby
route = router.recognize("/books")
route.routable? # => true
route.action # => ArgumentError: not delegated
```
```ruby
route = router.recognize("/books")
route.routable? # => false
route.action # => nil
```
=> `Hanami::Router#recognize` must return a non routeable route when a lazy endpoint cannot be resolved

spec/integration/hanami/router/mount_spec.rb, spec/integration/hanami/router/namespace_spec.rb, spec/support/fixtures.rb
Hi,
This might be an unnecessary fix as the router seems to accept any HTTP method and forward it gracefully to the back-end, but just in case, this ensures that the correct methods are being tested by the specs. It does not ensure, however, that all methods are tested.
This could be fixed by having a single source of truth for the list of HTTP methods, but I'm deep into unknown territory and don't know whether it would make sense, and if it did, where it should be stored or from what it should be extracted from.
=> Fix call to HTTP method named `unklink`

.rubocop.yml, lib/hanami/router.rb, lib/hanami/routing.rb, lib/hanami/routing/prefix.rb, lib/hanami/routing/resource/action.rb, lib/hanami/routing/scope.rb, spec/integration/hanami/router/scope_spec.rb, spec/support/fixtures.rb
**TL;DR:** In Hanami 1.x series we have inefficient routing, we want to make it efficient in 2.x.
---
We call the existing Hanami routing a **two-tier routing**. The first tier is for the Hanami project (let's say a `bookshelf` product), and the second tier is within a single app (`Web`, `Admin`, etc..). Imagine this as an "umbrella routing".
When a request to `/admin/people/23` comes in, the first tier (project router) decides which app should be routed to. Let's see this practically:
```ruby
Hanami.configure do
mount Admin::Application, at: "/admin"
mount Web::Application, at: "/"
end
```
Behind the code above, there is an `Hanami::Router` instance. The main responsibility of this router is to choose the right app, or to return a `404`.
Following the example above, the project tier …
=> Single tier routing for Hanami

lib/hanami/router.rb, lib/hanami/routing/endpoint.rb, lib/hanami/routing/prefix.rb, lib/hanami/routing/resource/action.rb, lib/hanami/routing/scope.rb, spec/integration/hanami/router/controller_integration_spec.rb, spec/integration/hanami/router/full_stack_application_spec.rb, spec/integration/hanami/router/nested_resources_spec.rb, spec/integration/hanami/router/prefix_option_spec.rb, spec/integration/hanami/router/prefix_spec.rb, spec/integration/hanami/router/resource_spec.rb, spec/integration/hanami/router/resources_spec.rb, spec/integration/hanami/router/scope_spec.rb, spec/support/fixtures.rb, spec/unit/hanami/router/new_spec.rb, spec/unit/hanami/router/recognize_spec.rb, spec/unit/hanami/routing/endpoint_spec.rb
This is a followup of #157. I tried to split the amount of changes between the two PRs, also because this one introduces a breaking change.
In order to make Hanami faster, since 2.0, the router will hold immutable action instances to serve all the incoming requests. With 1.x, it used to hold the action class and to create a new instance for each request.
Code sketch:
```ruby
@action.class # => Class
@action.name # => Web::Controllers::Home::Index
@action.new.call(env) # new instance for each request
@action.class # => Web::Controllers::Home::Index
@action.call(env) # always the same instance for all the requests
```
Given that `hanami-controller` 2.0 needs an instance of `Hanami::Controller::Configuration` to be instantiated, this PR introduces a new keyword `:controller` for …
=> Scope configuration

benchmarks/named_routes, benchmarks/resource, benchmarks/resources, benchmarks/routes, benchmarks/utils.rb
As a result of this https://github.com/hanami/utils/issues/259, the instance methods are here replaced by the class methods on the `develop` branch.
=> Replace Utils::String instance methods with class methods

lib/hanami/middleware/body_parser.rb, spec/integration/hanami/middleware/body_parser/parser_spec.rb
This is a narrowed-down PR based on the work I did in #180, focusing on the bug fix only, and leaving the refactoring work to be addressed in a separate follow-up PR.
This PR resolves #179. Now, when a `BodyParser` middleware is loaded, and the request’s content type does not match any of the loaded parser, it does not attempt to parse and symbolize the body. This ensures there will be no unexpected content in the resulting request env hash.
To make this concrete, given a `BodyParser` loaded, with `:json` as its only configured content type, when an ordinary x-www-form-urlencoded request comes through, it's body will _not_ be parsed, allowing Rack to parse it properly later on. This means we end up with params like this:
```ruby
{:hanami => "ok"}
```
And not like this:
```ruby
{:hanami => …
```
=> Skip attempting to parse unknown types in BodyParser middleware

lib/hanami/router.rb, spec/integration/hanami/router/context_spec.rb, spec/unit/hanami/router/new_spec.rb
Changes required for the new application router to work (as described in https://github.com/hanami/hanami/pull/1019).
=> Support for Hanami application router

lib/hanami/router/prefix.rb, spec/integration/hanami/router/mount_spec.rb, spec/integration/hanami/router/routing_spec.rb, spec/integration/hanami/router/scope_spec.rb
Given the following routes:
```ruby
Hanami::Router.new do
scope "foo" do
root to: ->(*) { [200, {}, ["Hello"]] }
end
end
```
**Before:**
```
GET /foo # 404 Not Found
GET /foo/ # 200 OK
```
**After:**
```
GET /foo # 200 OK
GET /foo/ # 404 Not Found
```
---
Ref hanami/api#8
=> Ensure scoped root to not be added as trailing slash

lib/hanami/router.rb, spec/support/fixtures.rb, spec/unit/hanami/router/not_allowed_spec.rb, spec/unit/hanami/router/not_found_spec.rb
We internally used constants to store serialized Rack responses for HTTP 404 and 405.
```ruby
NOT_FOUND = [404, { "Content-Length" => "9" }, ["Not Found"]].freeze
NOT_ALLOWED = [405, { "Content-Length" => "11" }, ["Not Allowed"]].freeze
```
In case of 404, the method was:
```ruby
def not_found
NOT_FOUND
end
```
It was returning the constant, **without duping**. When the Rack middleware were modifying the response headers the second element of the `NOT_FOUND` constant was **modified**.
The following 404 response were receiving the same headers of the first request. 😱 
It was accidentally caching the values because Hashes in Ruby are passed by reference. So the constant was **mutated** 🙀 
To prevent the _escaped_ (see Java Concurrency in Practice book) reference to be accidentally mutated …
=> Ensure to not accidentally cache response headers for HTTP 404 and 405

lib/hanami/router.rb, spec/unit/hanami/router/new_spec.rb
Allow `Hanami::Router` to be initialized without passing a block. This is useful when the router is assigned to a class variable and the class exposes a DSL to add routes, like in the case of `hanami-api`.
=> `Hanami::Router#initialize` do not yield block if not given

README.md, lib/hanami/router.rb, spec/unit/hanami/router/not_found_spec.rb
This adds `not_found` option which was present in 1.x and allowed to specify custom handler for when route was not recognized.
~~It was a bit tempting to choose better name (`default_handler` perhaps?), but I decided to stick with original name for this PR.~~
=> Add not_found option

lib/hanami/router.rb, lib/hanami/router/inspector.rb, lib/hanami/router/route.rb, spec/unit/hanami/router/inspector_spec.rb
* Ensure that the routes inspection is lazy, so the memory won't grow up unnecessary at the startup time when inspection isn't triggered.
* Transform `Hanami::Router::Inspector` into a mutable data object (it was a _callable object_) to ensure Hanami::API can use it.
* Introduce `Hanami::Router::Route` to resolve _data clump_ code smell.
---
Ref https://github.com/hanami/router/pull/208
=> Hanami::API inspector compat

hanami-router.gemspec, lib/hanami/router.rb, lib/hanami/router/formatter/human_friendly.rb, lib/hanami/router/inspector.rb, lib/hanami/router/route.rb, spec/unit/hanami/router/formatter/human_friendly_spec.rb, spec/unit/hanami/router/inspector_spec.rb
Up to this point, the route inspector always returned a visually
attractive representation of the routes. Now, that format has been
extracted to a `Hanami::Formatter::HumanFriendly` class, while others
are allowed to be injected.
That allows the creation of other algorithms that can be helpful for
purposes beyond a visual inspection, like CSV, JSON, or import formats
for API documentation and platforms.
As others can create their formatters, we're changing the visibility of
`Hanami::Inspector` and `Hanami::Route` methods to be public.
We've taken the occasion to refactor the extracted code, so it doesn't
mutate a variable. We've also removed the test on
`Hanami::Inspector#initialize` as it stated something obvious, and the
description was out of date since …
=> Extract formatter algorithm from the inspector

lib/hanami/router/formatter/csv.rb, lib/hanami/router/inspector.rb, spec/unit/hanami/router/formatter/csv_spec.rb, spec/unit/hanami/router/inspector_spec.rb
Adds a routes formatter that generates a CSV output.
We've changed the inspector to forward arguments to the underlying
formatter. In this particular case, it allows using [CSV generation
options](https://ruby-doc.org/stdlib-3.1.0/libdoc/csv/rdoc/CSV.html#class-CSV-label-Options+for+Generating).
=> Add CSV formatter

lib/hanami/middleware/body_parser/errors.rb, lib/hanami/middleware/error.rb
From a Hanami app while trying to use `Hanami::Middleware::BodyParser`
```
An error occurred while loading spec_helper.
Failure/Error: require "hanami/prepare"
NameError:
uninitialized constant Hanami::Middleware::Error
class BodyParsingError < Hanami::Middleware::Error
^^^^^^^
Did you mean?  IOError
Errno
```
=> Ensure to require `hanami/middleware/error` from `hanami/middleware/body_parser/errors`

lib/hanami/middleware/body_parser.rb, lib/hanami/middleware/body_parser/class_interface.rb, lib/hanami/middleware/body_parser/json_parser.rb, lib/hanami/middleware/body_parser/parser.rb, spec/integration/hanami/middleware/body_parser_spec.rb, spec/support/fixtures.rb, spec/unit/hanami/middleware/body_parser_spec.rb
- Allow passing mime types to the constructor of a Parser class
- Change `Parser#mime_types` to be `Parser.mime_types`
- Allow passing parser id along with additional mime types as an argument in the `BodyParser` constructor
=> Support configurable body parsers

hanami-router.gemspec
Keep up with latest dependencies.
This is a blocker for Ruby 3.2 compat.
=> Depend on `mustermann` and `mustermann-contrib` 3

lib/hanami/router.rb, lib/hanami/router/url_helpers.rb, spec/integration/hanami/router/prefix_option_spec.rb, spec/integration/hanami/router/routing_spec.rb, spec/support/generation_test_case.rb, spec/unit/hanami/router/new_spec.rb, spec/unit/hanami/router/url_spec.rb
There are subtle differences in behavior depending on whether it is a String or a URI. This patch forces it to be a URI and uses Prefix to construct absolute URLs.
I believe using strings for this was a mistake. The [public documentation](https://guides.hanamirb.org/v2.0/routing/overview/#named-routes) shows this as returning a URI object. This caused some spec churn, but I believe it is worth it for type consistency.
I propose using `Prefix` for this because it was built to do exactly what is needed here, and a path prefix on `base_url` is a very similar use-case to slice prefixes.
Fixes #249
=> UrlHelpers uses a consistent type for base_url

lib/hanami/middleware/node.rb, spec/unit/hanami/middleware/node_spec.rb
Issue reported here: https://github.com/hanami/api/issues/29
Explanation:
path segments are saved as String, even dynamic segments started with ":"
=> Fix find dynamic path segment for midlewares

.github/workflows/ci.yml
...and use a newer actions/checkout (to avoid any GitHub Actions warning about old stuff used)
=> CI: rely on setup-ruby to install

lib/hanami/router.rb, spec/integration/hanami/router/mount_spec.rb
If a mounted Rack app is at the root of the Hanami app, it should keep the leading slash in PATH_INFO, and the SCRIPT_INFO value should be blank. As per [the Rack spec on SCRIPT_INFO](https://github.com/rack/rack/blob/main/SPEC.rdoc):
> This may be an empty string, if the application corresponds to the
> “root” of the server.
The existing behaviour for apps mounted in sub-paths was fine - it's just the root path situation that wasn't being handled correctly. (As initially reported in #261)
I don't feel this is a particularly elegant fix (especially the spec changes), so please suggest changes (or, edit my commit!) if so desired.
=> fix PATH_INFO/SCRIPT_NAME for root mounts

.rubocop.yml, lib/hanami/middleware/app.rb, lib/hanami/router/errors.rb, spec/unit/hanami/middleware/app_spec.rb
Most middleware expect the old-school approach of hash options, but some are now using keyword arguments instead (such as Rack::Timeout). So let's presume that any keyword arguments that aren't known by Hanami should be passed through.
There is the edge-case of both the middleware and Hanami expecting arguments with the same name - this does not address that. 😓
This PR is paired with a forthcoming one for hanami/hanami, as that's where the various parameters are captured.
=> Pass through kwargs to middleware

lib/hanami/router.rb, lib/hanami/router/globbed_path.rb, lib/hanami/router/mounted_path.rb, spec/integration/hanami/router/mount_spec.rb, spec/unit/hanami/router/globbed_path_spec.rb, spec/unit/hanami/router/mounted_path_spec.rb
In the previous approach, globs would not be considered if a mounted app matched the route. On first glance this would be fair, but if that mounted app is at the root, and the glob is not, then even when the glob is listed first, it would be ignored (see #262).
But, a glob and a mount are not so different - they both have the potential to be far-reaching catch-all endpoints (though a glob is http_method-specific). So let’s handle them in the same collection, which helps keep their listed order in a routes file. This allows more-specific globs to be considered before a less-specific mount, provided they’re ordered that way in the routes.
This commit does not play so nicely with #263 - but the change there can be easily applied to MountedPath in this PR. Also, I realise there's potential …
=> group globs and mounts together

lib/hanami/router/leaf.rb, lib/hanami/router/node.rb, lib/hanami/router/trie.rb, spec/integration/hanami/router/recognition_spec.rb, spec/integration/hanami/router/scope_spec.rb, spec/unit/hanami/router/leaf_spec.rb, spec/unit/hanami/router/node_spec.rb, spec/unit/hanami/router/trie_spec.rb
@kyleplump and I collaborated on this PR.
Router cannot differentiate between multiple defined routes that contain different path variable names in the same location. For example:
```ruby
get "/:id/edit"
get "/:uuid"
```
This PR changes the router behavior to group all variable slugs together for matching purposes and to lazily create and evaluate Mustermann matchers. Discussion below.
The above symptom is illustrated in other open issues, such as #255 (Routes with multiple variables not working in common nested route scenario) and  #256 (Inconsistent trailing slash behaviour). Although trailing slashes are not a documented use case, they sometimes work (and sometimes don't) due to segment-by-segment matching.
The proposed implementation should close #255 , #256 , and #272 , by applying …
=> Improve Trie implementation when different path variables used in same path location

CHANGELOG.md, lib/hanami/router.rb, spec/unit/hanami/router/url_spec.rb
Given a scope (or by extension: a slice) which contains dash `-`, plus `+`, tilde `~` or dot `.` in their URL fragment:
```ruby
module Dashy
class Routes < Hanami::Routes
scope "my-scope" do
get "foo", to: "action.foo", as: :foo
end
end
end
```
The dashes etc. are converted to underscores for the corresponding URL helper name:
```
% hanami routes
GET   /my-slice/foo   action.foo   as :my_slice_foo
^^^                             ^^^
```
Closes #280
=> Convert dash (and more) to underscore in URL helper names

.github/workflows/ci.yml, Gemfile, spec/integration/hanami/router/routing_spec.rb
The Rack 2 tests are all failing (proving this is a necessary change!), due to Content-Length header being present when we expect it to be empty. That change was made in this commit: https://github.com/hanami/router/pull/277/commits/2323a3669b0a1053cda1840143518c370cb8777f, and related to this comment: https://github.com/hanami/router/pull/277#issuecomment-3142177837
~I think we don't want to change what we were doing for Rack 2, so we should set the response to have a Content-Length for Rack 2, and not have one for Rack 3? WDYT @timriley~
Update: so the issue was only for block responses. Rack 2 does set Content-Length for blocks, while [Rack 3 does not](https://github.com/rack/rack/blob/b68251c03788ff39d4a4b25424df7360426e4afd/lib/rack/response.rb#L114-L117), so I added a helper method …
=> Add Rack 2/3 to CI build matrix
